name: "dietgspp"

exp_root_dir: "outputs"
seed: 0

data_type: "none"
data:
  dataroot: ""
  downsample: -1
  zoom: -1
  n_test_traj_steps: -1

system_type: "dietgspp"
system:
  gaussian:
    dataroot: # Fill the data path
    model_path: # Fill the DiET-GS model path
    load_point: true

  vis_interval: 200

  start_sr_step: 20000
  num_sr_steps: 5000
  num_sync_steps: 20000
  sr_batch_size: 16
  patch_size: 128

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-x4-upscaler"
    prompt: "objects, high resolution, 4K, photo"
    spawn: false

  guidance_type: "stable-diffusion-upscaler-rsd-guidance"
  guidance:
    guidance_scale: 10.0
    half_precision_weights: true
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-x4-upscaler"
    anneal_strategy: "linear"
    min_step_percent: 0.5
    max_step_percent: 0.98
    anneal_end_step: ${system.num_sr_steps}
    anneal_start_step: 0
    step_ratio : 0.001
    guidance_type: 'rsd'
    t_min_shift_per_stage: 0.0 # min time shift per stage
    t_max_shift_per_stage: 0.0 # min time shift per stage
    cfg_shift_per_stage: 0.0
  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None  
      
  loss:
    lambda_rsd: 1.
    lambda_rgb: 1.

  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
      lr: 1e-2
    params:
      param:
        lr: 1e-2

trainer:
  max_steps: 3001
  val_check_interval: 1000000
  log_every_n_steps: 50000000
  num_sanity_val_steps: 0
  enable_progress_bar: true
  precision: 16-mixed
  limit_val_batches: 1
  limit_test_batches: 100

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.log_every_n_steps}
